//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZI.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrdersResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SZI.Orders.OrdersResource", typeof(OrdersResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutCropsOrder.
        /// </summary>
        internal static string CutCropsOrder {
            get {
                return ResourceManager.GetString("CutCropsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FertilizeOrder.
        /// </summary>
        internal static string FertilizeOrder {
            get {
                return ResourceManager.GetString("FertilizeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealCropsOrder.
        /// </summary>
        internal static string HealCropsOrder {
            get {
                return ResourceManager.GetString("HealCropsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOrder.
        /// </summary>
        internal static string NoOrder {
            get {
                return ResourceManager.GetString("NoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlantOrder.
        /// </summary>
        internal static string PlantOrder {
            get {
                return ResourceManager.GetString("PlantOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterOrder.
        /// </summary>
        internal static string WaterOrder {
            get {
                return ResourceManager.GetString("WaterOrder", resourceCulture);
            }
        }
    }
}
